apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: ingress
    component: frontend
  name: ingress-webapi
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # your subnets of instance, public subnets
    alb.ingress.kubernetes.io/subnets: 'subnet-00dd930ce53c8f46f, subnet-077ce0eb281b104bd, subnet-04a9613455ab9e1ca'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/security-groups: 'eks-alb'
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloapp-service
            port:
              number: 80

      - path: /webapi
        pathType: Prefix
        backend:
          service:
            name: webapi
            port:
              number: 80
